# Site settings

title: "Lyndsey Browning"
email: "lbrowning86@gmail.com"
description: "Lyndsey Browning's Personal Website"
baseurl: ""
url: "http://lyndseybrowning.github.io"
twitter_username: lbrowning86
github_username:  lyndseybrowning

# Build settings
markdown: kramdown
permalink: /posts/:title # lowercase separated by hyphens
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/posts/page:num"
exclude: ["node_modules", "gulpfile.js", "package.json"]
