# Site settings

title: "Lyndsey Browning"
email: "lbrowning86@gmail.com"
description: "Posts about JavaScript and Front End Development"
baseurl: ""
url: "http://lyndseyb.co.uk"
twitter_username: lbrowning86
github_username:  lyndseybrowning

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:title
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"
exclude: ["node_modules", "gulpfile.js", "package.json"]
